POST http://localhost:3002/items
Content-Type: application/json

 { "name":"Long Sleeved Shirt", "image_path":"images/KMC-LongSleeved.png", "description":"tEST", "price":"30000" }

###
GET http://localhost:3002/items/

###
GET http://localhost:3002/items?min=1&max=2

###