POST http://localhost:3002/vehicle
Content-Type: application/json

{ "name":"Articulated Bus",
"model":"Electric",
"length":"18m",
"type":"EVS",
"kind":"Bus",
"image_path":"/images/lowFloorEVS/18mArticulatedBus.jpg",
"seats":"90" }

###
GET http://localhost:3002/vehicle/type/EVS